version: "3"
services:

  envoy:
    image: envoyproxy/envoy
    volumes:
      - ./envoy.yaml:/tmp/envoy.yaml
    networks:
      - envoymesh
    expose:
      - 10000
      - 9901
    ports:
      - 10000:10000
      - 9901:9901
    command: envoy -c /tmp/envoy.yaml

  nginx1:
    image:  vaibhavthakur/nginx-vts:v1.0
    volumes:
      - ./nginx/nginx_1.html:/usr/share/nginx/html/nginx_1/index.html
      - ./nginx/nginx_1.conf:/etc/nginx/conf.d/default.conf
    networks:
      envoymesh:
        aliases:
          - nginx1
    expose:
      - 80
    ports:
      - 9090:80

  nginx2:
    image:  vaibhavthakur/nginx-vts:v1.0
    volumes:
      - ./nginx/nginx_2.html:/usr/share/nginx/html/nginx_2/index.html
      - ./nginx/nginx_2.conf:/etc/nginx/conf.d/default.conf
    networks:
      envoymesh:
        aliases:
          - nginx2
    expose:
      - 80
    ports:
      - 9091:80

  redis:
    image: redis:alpine
    expose:
      - 6379
    ports:
      - 6379:6379
    networks:
      envoymesh:
        aliases:
          - redis

  ratelimit:
    build:
      context: .
      dockerfile: ratelimit.dockerfile
    image: ratelimit
    command: ratelimit
    volumes:
      - ./ratelimit_config.yaml:/ratelimit/config/config.yaml
    ports:
      - 8080:8080
      - 8081:8081
      - 6070:6070
    depends_on:
      - redis
    networks:
      envoymesh:
        aliases:
          - ratelimit
    environment:
      - USE_STATSD=false
      - LOG_LEVEL=debug
      - REDIS_SOCKET_TYPE=tcp
      - REDIS_URL=redis:6379
      - RUNTIME_ROOT=/
      - RUNTIME_SUBDIRECTORY=ratelimit/config

networks:
  envoymesh: {}
